### ISSUE TITLE
Minor Missing Items

### ISSUE THREAD

**Issue by SteveToms** [aurooba/wpaudit.site#10]
A security plugin is always a good idea. WordFence, iThemes Security etc.

Analytics. Ensure you can have analytics turned on.

Privacy Policy. Always a good idea to have even a basic one.

And ensure any API, captcha and license keys are setup for live domain.

**Comment by aurooba** [comment]
Thanks for this @SteveToms! Going to add this to a new section I'll be setting up today.

**Comment by Zodiac1978** [comment]
> A security plugin is always a good idea. WordFence, iThemes Security etc.

I would not recommend to do this. People without knowledge could produce more problems than are solved.

> Analytics. Ensure you can have analytics turned on.

At least in Europe this is only allowed after an opt-in (explicit consent needed). And there are other things to consider (IP anonymization, Opt-out, etc.)

> Privacy Policy. Always a good idea to have even a basic one.

+1 - this is (at least) needed for all German websites. Additionally to a legal page about the site owner with contact info and more.

> And ensure any API, captcha and license keys are setup for live domain.

+1

**Comment by aurooba** [comment]
@SteveToms wanna do a PR for some of these items? That way you'll show up as a contributor. If not, let me know! I'm planning on adding a host of improvements/additions to the site this weekend. Offer open to anyone (looking at you @Zodiac1978)!
