### ISSUE TITLE
Test forms

### ISSUE THREAD

**Issue by aurooba** [aurooba/wpaudit.site#22]
Suggestion from @courtneyr-dev [on Twitter](https://twitter.com/courtneyr_dev/status/1503792609927565323?s=20&t=IF5NWqiKs0lXPfT4S86DWw)

**Comment by courtneyr-dev** [comment]
> Suggestion from @courtneyr-dev [on Twitter](https://twitter.com/courtneyr_dev/status/1503792609927565323?s=20&t=IF5NWqiKs0lXPfT4S86DWw)

Thanks! I forgot to swing back to log it.

**Comment by aurooba** [comment]
[Suggested link](https://wpforms.com/form-testing-checklist/) to share for testing forms from @courtneyr-dev! Thanks Courtney! :)

**Comment by aurooba** [comment]
Closed by 8c3190e29212c3782fd7bdb7bec9548bc0cac5a0
