### ISSUE TITLE
Link in "Did ya set up search tracking?" seems wrong

### ISSUE THREAD

**Issue by Zodiac1978** [aurooba/wpaudit.site#27]
It shows this text and link:
[A Privacy Policy for your Website](https://ahrefs.com/) – a decent overview of what your privacy policy should cover.

But https://ahrefs.com/ is not the privacy policy article I would expect. ;)

**Comment by aurooba** [comment]
I do believe this was fixed in a previous commit @Zodiac1978! Thanks for highlighting it. :)
