### ISSUE TITLE
brotli missing

### ISSUE THREAD

**Issue by DanielRuf** [aurooba/wpaudit.site#4]

**Comment by aurooba** [comment]
Not gonna lie, I had to look this one up. Shall have to learn more about it first!

**Comment by DanielRuf** [comment]
Ah, forgot to add the details:

https://caniuse.com/#feat=brotli

The recommended way are statically compiled brotli assets with a compression levle of `9` (there are benchmarks, 11 takes much longer but improves the performance less than 9).
