### ISSUE TITLE
webp missing

### ISSUE THREAD

**Issue by DanielRuf** [aurooba/wpaudit.site#5]

**Comment by aurooba** [comment]
Also another slightly tough one to suggest implementation for. But still a good point.

**Comment by DanielRuf** [comment]
I have used https://wordpress.org/plugins/webp-express/ and the official webp and / or imagemagick / graphicsmagick (available on most hosting providers) for most websites.

**Comment by aurooba** [comment]
Opening this back up since webp is supported in wordpress and there's more stuff around this now! :) @DanielRuf it's been a while, but did you want to submit a PR with suggestions and some text?

**Comment by DanielRuf** [comment]
Sorry, I was quite busy. The commited changes are perfect. Thank you very much.

**Comment by aurooba** [comment]
Totally fine! Thank you for the suggestions!
