### ISSUE TITLE
do not reduce requests by combining files

### ISSUE THREAD

**Issue by DanielRuf** [aurooba/wpaudit.site#7]
With http2 there is one connection used for all requests. This should improve the loading speed to.

Discourage file concatenation used by some plugins.

**Comment by aurooba** [comment]
Hmm. I think including this would require some more explanation and good links. I'll think on it. :) Also it can be tough to control what plugins do.

**Comment by DanielRuf** [comment]
It depends, in some optimization and cache plugins this can be enabled / disabled (concatenation and bundling of files). Often this also increases the FFTB metrics which hurts the performance.
