### ISSUE TITLE
use locally hosted webfonts

### ISSUE THREAD

**Issue by DanielRuf** [aurooba/wpaudit.site#8]

**Comment by aurooba** [comment]
*when able. But yes! I'll be doing a round of updates soon hopefully and incorporate it :)

**Comment by DanielRuf** [comment]
There are a few good plugins:

https://wordpress.org/plugins/host-webfonts-local/
https://wordpress.org/plugins/host-google-fonts-locally/

I have used https://wordpress.org/plugins/selfhost-google-fonts/ on a few websites and it should still work too.
