### ISSUE TITLE
recommend NinjaFirewall

### ISSUE THREAD

**Issue by DanielRuf** [aurooba/wpaudit.site#9]
Limit Login Attempts does not really protect.

Recommend a real WAF - NinjaFirewall.

**Comment by aurooba** [comment]
You're right, but it does to the trick for manual hacks a bit. I'll look into NinjaFirewall!

**Comment by DanielRuf** [comment]
You are right, but better be safe(r) than sorry =)
Should be combined with NinjaScanner =)

**Comment by aurooba** [comment]
@DanielRuf I haven't forgotten about these, by the way! I'm hoping to address these and add improvements to WPAudit in May. :)

**Comment by aurooba** [comment]
Thinking of including [this NinjaFirewall plugin](https://wordpress.org/plugins/ninjafirewall/). Thoughts @DanielRuf?

**Comment by DanielRuf** [comment]
Correct, this is the WordPress plugin that I mean.

I have also a default configuration with some settings at https://danielruf.github.io/ninjafirewall-config-browser/ (code is at https://github.com/DanielRuf/ninjafirewall-config-browser/blob/master/src/config/config.json).
